[package]
name = "tailsrv"
version = "0.3.0"
description = "A high-performance file-streaming server"
readme = "README.md"
repository = "https://git.sr.ht/~asayers/tailsrv"
license = "Unlicense"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
edition = "2018"

[dependencies]
inotify = "0.9.3"
log = "0.4.14"
loggerv = "0.7.2"
nix = "0.22.0"
structopt = "0.3.22"
tokio = { version = "1.9.0", features = ["full"] }
