[package]
name = "tailsrv"
version = "0.3.0"
description = "A high-performance file-streaming server"
readme = "README.md"
repository = "https://git.sr.ht/~asayers/tailsrv"
license = "Unlicense"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
nix = "0.23.1"
notify = "5.0.0-pre.13"
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
