[package]
name = "tailsrv"
version = "0.4.0"
description = "A high-performance file-streaming server"
readme = "README.md"
repository = "https://git.sr.ht/~asayers/tailsrv"
license = "Unlicense"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
nix = "0.24.2"
notify = "5.0.0-pre.15"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.6"
