[package]
name = "tailsrv"
version = "0.3.0"
description = "A high-performance file-streaming server"
readme = "README.md"
repository = "https://git.sr.ht/~asayers/tailsrv"
license = "Unlicense"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.27"
error-chain = "0.11"
fs2 = "0.4"
ignore = "0.3"
integer-encoding = "1.0"
log = "0.3"
loggerv = "0.5"
memchr = "2.0"
memmap = "0.6"
mio = "0.6"
mio-more = "0.1"
nix = "0.9"
nom = "3.2"
same-file = "1.0"
slab = "0.4"

[dependencies.inotify]
branch = "master"
features = ["mio"]
git = "https://github.com/asayers/inotify-rs"
