[package]
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
name = "tailsrv"
version = "0.1.0"

[dependencies]
clap = "2.26.0"
env_logger = "0.4.3"
error-chain = "0.10.0"
ignore = "0.2.2"
log = "0.3.8"
mio = "0.6.10"
nix = "0.9.0"
nom = "3.2.0"
same-file = "0.1.3"

[dependencies.inotify]
branch = "master"
features = ["mio"]
git = "https://github.com/asayers/inotify-rs"
